### PR TITLE
Run statement

### PR DESCRIPTION
**Pull request by PeterJudgeZA**
Support RUN statements with a specific token for the hard-coded program being run. Programs run with `VALUE()`  will have the VALUe and contents processed as a function.

New token for the program being run: `meta.other.procedure.abl` .

Related to this comment https://github.com/vscode-abl/vscode-abl/issues/77#issuecomment-1936256928

### CODE REVIEW

**Comment by chriscamicas** [comment]
hi @PeterJudgeZA thanks for the fix, there are conflicts with the main branch, could you resolve them before I could merge?
Thank you

**Comment by PeterJudgeZA** [comment]
@chriscamicas Checks are passing now.

**Comment by chriscamicas** [comment]
checks are passing but there are remaining conflicts 
image

**Comment by PeterJudgeZA** [comment]
@chriscamicas Not to play ping-pong but I am seeing no conflicts at the moment?

**Comment by gquerret** [comment]
@PeterJudgeZA This is because Christophe wants to "Rebase and merge". The problem here is that there's a merge commit in the set.

**Comment by PeterJudgeZA** [comment]
Ok, I think I have it right this time, thanks to @gquerret

**Pull request merged**
