### PR TITLE
Vscode-abl issue#66 : add support for OOABL types

### PR DESCRIPTION
**Pull request by PeterJudgeZA**
https://github.com/vscode-abl/vscode-abl/issues/66 

Or at least, that's how it started.  Many changes happened along the way.

Changes include, but are not limited to:
- Support for OOABL types, including generic types, specific functions like TYPE-OF and CAST
- Separated ABL language attributes and functions into their own tokens
- Improved test reporting (so that the tokens are included in the output)
- Multiple tests were updated (with more details)
- New tests added for OOABL type support

### CODE REVIEW

**Comment by chriscamicas** [comment]
Thank you very much @PeterJudgeZA for amazing contribution!
Could you please rebase your branch on master, I updated the Azure DevOps pipeline with latest Ubuntu/Node version so checks will now be able to pass on Github side 🙏

**Comment by PeterJudgeZA** [comment]
@chriscamicas I've updated my branch, and checks are passing now ...

**Comment by gquerret** [comment]
I think a rebase would be better 😄

**Comment by PeterJudgeZA** [comment]
@chriscamicas  Any chance of formatting the abl.tmLanguage.json file with the "TextMate Syntax Highlighting and Intellisense" VS Code extension? Otherwise I'll JSON-format it and do the rebase on that basis ...

**Comment by chriscamicas** [comment]
Sure @PeterJudgeZA , let's do this, but in a separate PR please 🙏

**Comment by PeterJudgeZA** [comment]
Ok, I think I've got this rebased now. Think.

**Comment by gquerret** [comment]
Not really rebased... I'll contact you offline

**Comment by PeterJudgeZA** [comment]
The beauty of git is that everyone can see your "fixed this" , "nope, really fixed this", "no really really fixed this" type comments.

So I will say that I think I have rebased successfully (until  @gquerret  tells me otherwise).

**Comment by gquerret** [comment]
There's a hint here:
image

**Comment by gquerret** [comment]
I'll call you on Monday for this PR. Just one question: I didn't find any format option in the "TextMate Syntax Highlighting and Intellisense". Are you sure this is required ? Is there any issue with the standard JSON formatter ? I've formatted `abl.tmLanguage.json` and it stays identical, so it's probably already ok. 

> The beauty of git is that everyone can see your "fixed this" , "nope, really fixed this", "no really really fixed this" type comments.

This is why commits are usually squashed before opening a PR.

**Pull request closed without merging**
