### PR TITLE
Comment in block statement

### PR DESCRIPTION
**Pull request by PeterJudgeZA**
Support for comments in block statements, like the below
```abl
repeat while i < 10 /* only this
                       many digits */ :
```

### CODE REVIEW

**Comment by gquerret** [comment]
Where is GitHub syntax highlight coming from ?
image

**Comment by chriscamicas** [comment]
[GitHub Linguist lib](https://github.com/github-linguist/linguist), which is used for syntax highlighting, uses this grammar for the ABL Language. 😊 
Look [here](https://github.com/github-linguist/linguist/blob/master/vendor/README.md), and search for "OpenEdge ABL"

**Comment by gquerret** [comment]
> [GitHub Linguist lib](https://github.com/github-linguist/linguist), which is used for syntax highlighting, uses this grammar for the ABL Language. 😊 Look [here](https://github.com/github-linguist/linguist/blob/master/vendor/README.md?rgh-link-date=2024-06-17T08%3A45%3A55Z), and search for "OpenEdge ABL"

Nice ! But that means the current grammar should be fixed, syntax highlight does not look good on this code sample...

**Comment by PeterJudgeZA** [comment]
> > [GitHub Linguist lib](https://github.com/github-linguist/linguist), which is used for syntax highlighting, uses this grammar for the ABL Language. 😊 Look [here](https://github.com/github-linguist/linguist/blob/master/vendor/README.md?rgh-link-date=2024-06-17T08%3A45%3A55Z), and search for "OpenEdge ABL"
> 
> Nice ! But that means the current grammar should be fixed, syntax highlight does not look good on this code sample...

@chriscamicas I found that the other day, it's very cool. 

@gquerret I don't know why the highlighting wasn't working properly. Even before this PR, the highlighting should have been better. 

I added 'abl' to the comment , as in \`\`\`abl  and that's the formatting that was applied.

**Comment by chriscamicas** [comment]
> > [GitHub Linguist lib](https://github.com/github-linguist/linguist), which is used for syntax highlighting, uses this grammar for the ABL Language. 😊 Look [here](https://github.com/github-linguist/linguist/blob/master/vendor/README.md?rgh-link-date=2024-06-17T08%3A45%3A55Z), and search for "OpenEdge ABL"
> 
> Nice ! But that means the current grammar should be fixed, syntax highlight does not look good on this code sample...

Definitely we have to make sure the master branch is clean and works as expected not to break github (<- no pressure 😅 )

**Comment by gquerret** [comment]
Cherry-picked commits and pushed to 1.3.1

**Pull request closed without merging**
